server:
  port: 8085
spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/user/**
          filters:
            - RewritePath=/api/user(?<segment>/?.*), /api/user-service/$\{segment}
        - id: product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/product(?<segment>/?.*), /api/product-service/$\{segment}
